#!/bin/bash

echo "🚀 Setting up QAVibe Documentation Automation"
echo "=============================================="

echo ""
echo "📋 Required GitHub Repository Setup:"
echo ""
echo "1. 🔐 Create a Personal Access Token (PAT) with these permissions:"
echo "   - repo (full control of private repositories)"
echo "   - workflow (update GitHub Action workflows)"
echo ""
echo "2. 🔧 Add the PAT as a repository secret:"
echo "   - Go to: Settings > Secrets and variables > Actions"
echo "   - Name: PRIVATE_REPO_TOKEN"
echo "   - Value: Your PAT from step 1"
echo ""
echo "3. 📄 Enable GitHub Pages:"
echo "   - Go to: Settings > Pages"
echo "   - Source: Deploy from a branch"
echo "   - Branch: main / (root)"
echo ""
echo "4. 🔗 Optional: Set up webhooks for real-time updates"
echo "   In your private repos (testflux & stackhealth):"
echo "   - Go to: Settings > Webhooks > Add webhook"
echo "   - Payload URL: https://api.github.com/repos/apercallc/qavibeapp/dispatches"
echo "   - Content type: application/json"
echo "   - Secret: (create a webhook secret and add as WEBHOOK_SECRET repository secret)"
echo "   - Events: Push events to main branch"
echo ""
echo "5. 📁 Directory Structure Created:"
echo "   ├── .github/workflows/sync-docs.yml    (Auto-sync workflow)"
echo "   ├── scripts/generate-changelog.js      (Changelog processor)"
echo "   ├── docs/products/                     (Synced documentation)"
echo "   │   ├── testflux/                      (TestFlux docs)"
echo "   │   └── stackhealth/                   (StackHealth docs)"
echo "   └── public/docs/                       (Public documentation site)"
echo ""
echo "🎯 Next Steps:"
echo ""
echo "1. Complete the GitHub setup steps above"
echo "2. Run the workflow manually to test: Actions > Sync Documentation > Run workflow"
echo "3. Check the generated documentation at: https://apercallc.github.io/qavibeapp/docs/"
echo "4. The workflow will run every 6 hours automatically"
echo ""
echo "📝 Workflow Features:"
echo "• ✅ Pulls docs/ folder from both private repos"
echo "• ✅ Combines changelogs with date sorting"
echo "• ✅ Creates filterable changelog page"
echo "• ✅ Maintains private code security"
echo "• ✅ Auto-updates every 6 hours"
echo "• ✅ Manual trigger available"
echo "• ✅ Webhook support for real-time updates"
echo ""
echo "🔧 Customization:"
echo "• Edit scripts/generate-changelog.js to modify changelog format"
echo "• Edit public/docs/index.html to customize documentation layout"
echo "• Modify .github/workflows/sync-docs.yml to change sync frequency"
echo ""
echo "✨ Setup complete! Check the GitHub repository for next steps."
